name: C++ CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Google Test
        run: |
          sudo apt update
          sudo apt install -y make libgtest-dev

      - name: Build
        run: make

      - name: Run tests
        run: make run
      
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-results.xml